### ISSUE TITLE
white list renti.co

### ISSUE THREAD

**Issue by staugaard** [spamscanner/spamscanner#12]
`Link hostname of "renti.co" was detected by Cloudflare's Family DNS to contain adult-related content, phishing, and/or malware.`

renti.co is safe. It's a property rental application system.

please whitelist renti.co

**Comment by niftylettuce** [comment]
Can you please file the request here? https://report.teams.cloudflare.com/

**Comment by niftylettuce** [comment]
I've implemented 1 hour caching and reset cache on my side, so once they update their side you should be good.
