### ISSUE TITLE
Hostname is classified incorrectly.

### ISSUE THREAD

**Issue by gjonikas** [spamscanner/spamscanner#6]
Hi all,

I'm using forwardemail.net service for www.pricedout.org.uk domain, and occasionally when sending emails from this domain I get the following error:

 420 Error for support@forwardemail.net of "Link hostname of "pricedout.org.uk" was detected by Cloudflare's Family DNS to contain adult-related content, phishing, and/or malware. Phishing whitelist requests can be filed at https://github.com/spamscanner/spamscanner/issues." If you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net. 

AFAIK, the emails usually go through just fine and the misclassifications seems to happen intermittently.

Would it be possible to somehow whitelist this domain?

Many thanks.

**Comment by niftylettuce** [comment]
Seems like there is a NS lookup issue on pricedout.org.uk:

```sh
❯ curl "https://family.cloudflare-dns.com/dns-query?name=pricedout.org.uk&type=A" -H "Accept: application/dns-json" -H "User-Agent: forwardemail/test"
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"pricedout.org.uk","type":1}]}

❯ curl "https://family.cloudflare-dns.com/dns-query?name=www.pricedout.org.uk&type=A" -H "Accept: application/dns-json" -H "User-Agent: forwardemail/test"
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"www.pricedout.org.uk","type":1}],"Answer":[{"name":"www.pricedout.org.uk","type":5,"TTL":3571,"data":"ghs.googlehosted.com."},{"name":"ghs.googlehosted.com","type":1,"TTL":271,"data":"172.217.1.243"}]}
```

**Comment by niftylettuce** [comment]
Though this wouldn't cause that error to occur.  Let me check something.

**Comment by niftylettuce** [comment]
I've emailed my higher-level contact at Cloudflare to investigate this.

**Comment by niftylettuce** [comment]
In the meanwhile, I suggest setting an A record for your hostname without the www.

e.g. `dig pricedout.org.uk a` should return the same that `dig www.pricedout.org.uk a` returns

Also when you visit pricedout.org.uk you should have it redirect to the www, either use www and enforce it when people visit non-www, or the reverse.  Don't have both and definitely have both work in terms of redirection to the other.

**Comment by gjonikas** [comment]
Awesome. Thanks for your help!

**Comment by niftylettuce** [comment]
I heard back from cloudflare.  they said your domain was not flagged and is classified as real estate

also they said that one-off edge cases are a possibility:

> We have seen some rare instances where the key value store on our edge network that applies the logic has errors on a one-off basis.
