### ISSUE TITLE
Request to remove about.chatroulette.com 

### ISSUE THREAD

**Issue by gvolpe** [spamscanner/spamscanner#7]
I got this error response when linking the site https://about.chatroulette.com/solutions/. I know https://chatroulette.com/ is categorized as adult content (hey, working on changing this!) but is there any chance subdomains are not detected as adult-related content? 

```
420 Error for orgateam@nixcon.org of "Link hostname of "about.chatroulette.com" was detected by Cloudflare's Family DNS to contain adult-related content, phishing, and/or malware. Phishing whitelist requests can be filed at https://github.com/spamscanner/spamscanner/issues." If you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net.
```

**Comment by niftylettuce** [comment]
I'm sorry but there would be too many workarounds.  I suggest to put the about page on a separate domain if possible, and do a 301 redirect from that page to the new domain.

**Comment by gvolpe** [comment]
No problems, thanks for replying :+1:

**Comment by niftylettuce** [comment]
is that a feasible solution for you @gvolpe?

**Comment by gvolpe** [comment]
That is actually a good idea, yes. I'll propose that to the management :+1:

**Comment by gvolpe** [comment]
Just came to the conclusion a redirect wouldn't help if the domain is still blocked. That's the case for some universities, for example.

**Comment by niftylettuce** [comment]
you would point the links to the new domain, and the existing domain would
redirect 301 to the new one
