### ISSUE TITLE
False malicious classification of hostname

### ISSUE THREAD

**Issue by akash14darshan** [spamscanner/spamscanner#8]
My host parabellum.ga has been classified as malicious

The response from the remote server was:
420 Error for support@parabellum.ga of "Link hostname of "parabellum.ga" was detected by Cloudflare's Family DNS to contain adult-related content, phishing, and/or malware. Phishing whitelist requests can be filed at https://github.com/spamscanner/spamscanner/issues." If you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net.

**Comment by niftylettuce** [comment]
I will reach out to my contacts at Cloudflare and have this resolved, one moment.

**Comment by niftylettuce** [comment]
ref https://github.com/spamscanner/spamscanner/issues/9

I already submitted it as gaming, will follow up once done

**Comment by niftylettuce** [comment]
resolved.
